### ISSUE TITLE
Youtube datasets

### ISSUE THREAD

**Issue by liu0527aa** [vztu/BVQA_Benchmark#3]
Hello, can you help  upload the YouTube dataset to Baidu Cloud Disk? I met some problems (some videos failed to download) while downloading these videos from the Google cloud platform. Thank you very much!

**Comment by liu0527aa** [comment]
Also, due to hard drive limitations, I downloaded the H.264 video. However, I found that its total number of videos doesn't match the 1,381 you mentioned.It only has 1263 clips of videos. Do you use the original video?

**Comment by vztu** [comment]
Hi @liu0527aa, YouTube UGC dataset is being updated monthly due to license issues. I used the first version of RAW videos (~3TB) for experiments reported in my paper. It may not be easy for me to upload 3TB to Baidu Disk, so you'd have to find a way to download yourself. I think it's okay for you to download use the H264 version (since it's much smaller), but for a fair comparison, you'd better train other models as well on your own copy of dataset.
